### ISSUE TITLE
"Best discord webhook spammer" bruh perryhook is way better

### ISSUE THREAD

**Issue by master7720** [Its-Vichy/MrHook#1]

**Comment by Its-Vichy** [comment]
Haha, the code is horrible, with a lot of useless comments, the design is disgusting and completely copied on another [github repos](https://github.com/cattyngmd/cutehook) :,). MrHook was disigned a long time ago and is an powerfull tool that can use proxy and support multiple urls lmao :)

I think you are just fanboy of an skid and you whant to promote this shit tools, MrHook is just disigned to spam and he successfully make this job.

You can easily ratelimit an webhook you d'ont need to send 9999 requests / s :,)

**Comment by Zane2b2t** [comment]
Master im looking for perry hook but ofc perry deleted his github can u send
